#!/usr/bin/env python3
"""Generate the Subconverter external TOML configuration from the primary INI."""

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def quote(value):
    return json.dumps(value, ensure_ascii=False)


def render():
    settings, groups, rulesets = {}, [], []
    for line in (ROOT / "baixiaosheng.ini").read_text().splitlines():
        line = line.strip()
        if not line or line.startswith((";", "#", "[")):
            continue
        key, value = line.split("=", 1)
        if key == "ruleset":
            rulesets.append(value.split(",", 1))
        elif key == "custom_proxy_group":
            fields = value.split("`")
            name, kind = fields[:2]
            group = {"name": name, "type": kind}
            rules = fields[2:]
            if kind in ("url-test", "fallback", "load-balance"):
                group["url"] = rules[-2]
                times = rules[-1].split(",")
                group["interval"] = int(times[0])
                if kind == "url-test" and len(times) > 2 and times[2]:
                    group["tolerance"] = int(times[2])
                if kind == "load-balance":
                    # Upstream INI parsing defaults to consistent-hashing.
                    group["strategy"] = "consistent-hashing"
                rules = rules[:-2]
            group["rule"] = [rule for rule in rules if rule]
            groups.append(group)
        else:
            settings[key] = value
    lines = [
        "# Generated by scripts/sync_config.py from baixiaosheng.ini.",
        "# Edit the INI first; this is a Subconverter external config.",
        "version = 1", "", "[custom]",
    ]
    for key, value in settings.items():
        lines.append(f"{key} = {value if value in ('true', 'false') else quote(value)}")
    for group in groups:
        lines.extend(("", "[[custom_groups]]"))
        for key, value in group.items():
            if isinstance(value, list):
                encoded = "[" + ", ".join(quote(v) for v in value) + "]"
            elif isinstance(value, int):
                encoded = str(value)
            else:
                encoded = quote(value)
            lines.append(f"{key} = {encoded}")
    for group, source in rulesets:
        lines.extend(("", "[[rulesets]]", f"group = {quote(group)}",
                      f"ruleset = {quote(source)}"))
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if TOML is out of sync")
    args = parser.parse_args()
    target = ROOT / "baixiaosheng.toml"
    expected = render()
    if args.check:
        if not target.exists() or target.read_text() != expected:
            parser.exit(1, "TOML is out of sync; run python3 scripts/sync_config.py\n")
        print("INI/TOML synchronization: OK")
    else:
        target.write_text(expected)
        print("Updated baixiaosheng.toml")


if __name__ == "__main__":
    main()
